#!/bin/bash

for i in {0..10}; do
    ./lemipc "$PWD" 1 &
done

for i in {0..10}; do
    ./lemipc "$PWD" 2 &
done

for i in {0..10}; do
    ./lemipc "$PWD" 3 &
done

for i in {0..10}; do
    ./lemipc "$PWD" 4 &
done

for i in {0..10}; do
    ./lemipc "$PWD" 5 &
done

for i in {0..10}; do
    ./lemipc "$PWD" 6 &
done

for i in {0..10}; do
    ./lemipc "$PWD" 7 &
done

make fclean
